# Ruby CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run: bundle exec rspec
