# Ruby CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.6.3
         environment:
           RAILS_ENV: test
           RACK_ENV: test
       - image: circleci/postgres:11.5
         environment:
           POSTGRES_USER: postgres

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install `psql` command
          command: sudo apt-get update && sudo apt-get install postgresql-client
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
