name: checks

on: [push, pull_request]

jobs:
  checks:
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      RAILS_ENV: test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        # TODO: expand to more? 3.2.0, 3.0.5
        ruby-version: [2.7.7, 3.1.3]
        activerecord-version: [4.2.11.3, 7.0.4]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install ActiveRecord version ${{ matrix.activerecord-version }}
      run: gem install activerecord -v ${{ matrix.activerecord-version }}
    # - name: Lint
    #   run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
